name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  google_fonts: ^8.0.1
  lottie: ^3.3.2
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^20.1.0
  workmanager: ^0.9.0+3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
